export const LIST_KEYS = [
"Date descriptor",
"Co-offenders",
"Reason for inclusion",
"Jurisdiction",
"Location: state",
"People vs. property",
"Physical target",
"Ideological target",
"Ideological affiliation",
"Affiliation with FTO",
"Hate Crime",
"LEO Informant",
"Previous similar crime",
"Criminal method",
"Additional criminal method",
"Completion of crime",
"Plea",
"Verdict",
"Gender",
"Other' status",
"Racial/ethnic group",
"Religion",
"Veteran status",
"Combat veteran",
"Citizenship status",
]

export const SEARCH_BY_KEYS = [
    "Any",
    "Charges",
    "Plea",
    "Group affiliation",
    "Full legal name",
    "Other names/aliases",
    "Name of case",
    "Location: country",
    "Location: state",
    "Location: city"
]