export const SHEET_NAMES = {
    General: "General",
    J20: "J20 cases",
    "Summer-Fall 2020 Protests":"Summer-Fall 2020 protest cases",
    "Capitol Raid":"Capitol raid cases"
  };

export const DROPDOWN_KEYS = [
    "Date descriptor",
    "Co-offenders",
    "Reason for inclusion",
    "Jurisdiction",
    "Location: state",
    "People vs. property",
    "Physical target",
    "Ideological target",
    "Ideological affiliation",
    "Affiliation with FTO",
    "Hate Crime",
    "LEO Informant",
    "Previous similar crime",
    "Criminal method",
    "Additional criminal method",
    "Completion of crime",
    "Plea",
    "Verdict",
    "Gender",
    "Other' status",
    "Racial/ethnic group",
    "Religion",
    "Veteran status",
    "Combat veteran",
    "Citizenship status",
]

export const SEARCH_BY_KEYS = [
    "Any",
    "Charges",
    "Plea",
    "Group affiliation",
    "Full legal name",
    "Other names/aliases",
    "Name of case",
    "Location: country",
    "Location: state",
    "Location: city"
]

export const SEARCH_BY_KEYS_MOBILE = [
    "Any",
    "Date",
    "Full legal name", 
    "Group affiliation",
    "Ideological affiliation",
    "Length of prison sentence"
]

export const RESULTS_PER_PAGE_KEYS = [
    "10",
    "25", 
    "50",
    "100"
]

export const MOBILE_COLUMN_KEYS = [
    "Date",
    "Full legal name", 
    "Group affiliation",
    "Ideological affiliation",
    "Length of prison sentence"
]

export const TABLE_WIDTH_MAP = {
  "Date": "mobile-w-28 w-40",
  "Date descriptor": "w-52",
  "Case ID": "w-52",
  "Group identifier": "w-52",
  "Full legal name": "mobile-w-40 w-52",
  "First name": "w-40",
  "Family name": "w-40",
  "Other names/aliases": "w-64",
  "Co-offenders": "w-40",
  "Reason for inclusion": "w-96",
  "Name of case": "w-72",
  "Jurisdiction": "w-64",
  "Location: country": "w-52",
  "Location: state": "w-52",
  "Location: city": "w-52",
  "People vs. property": "w-64",
  "Physical target": "w-64",
  "Ideological target": "w-72",
  "Ideological affiliation": "mobile-w-48 w-72",
  "Affiliation with FTO": "w-52",
  "Group affiliation": "mobile-w-48 w-72",
  "Hate Crime": "w-40",
  "LEO Informant": "w-40",
  "Previous similar crime": "w-40",
  "Criminal method": "w-72",
  "Additional criminal method": "w-72",
  "Completion of crime": "w-64",
  "# killed": "w-40",
  "# injured": "w-40",
  "Charges": "w-96",
  "Plea": "w-52",
  "Verdict": "w-52",
  "Length of prison sentence": "mobile-w-40 w-52",
  "Life sentence": "w-52",
  "Death sentence": "w-52",
  "Additional details": "w-72",
  "Age": "w-52",
  "Gender": "w-52",
  "Other' status": "w-52",
  "Racial/ethnic group": "w-64",
  "Religion": "w-52",
  "Veteran status": "w-52",
  "Combat veteran": "w-40",
  "Service Classification": "w-52",
  "Citizenship status": "w-52",
  "Short narrative": "w-96",
  "Name of coder(s)": "w-64",
  "Source description": "w-72",
  "Audited": "w-52",
  "Date of last review": "w-52",
  "Ready": "w-52",
  "Claimed": "w-52",
  "Complete": "w-52",
  "Questionable Inclusion": "w-52",
  "Tags": "w-64"
}

export const TABLE_WIDTH_MAP_MOBILE = {
    "Date": "w-20",
    "Full legal name": "w-20",
    "Ideological affiliation": "w-20",
    "Group affiliation": "w-20",
    "Length of prison sentence": "w-20"
  }

export const DESKTOP_COLUMN_KEYS = [
    "Date",
    "Date descriptor",
    "Case ID",
    "Group identifier",
    "Full legal name",
    "First name",
    "Family name",
    "Other names/aliases",
    "Co-offenders",
    "Reason for inclusion",
    "Name of case",
    "Jurisdiction",
    "Location: country",
    "Location: state",
    "Location: city",
    "People vs. property",
    "Physical target",
    "Ideological target",
    "Ideological affiliation",
    "Affiliation with FTO",
    "Group affiliation",
    "Hate Crime",
    "LEO Informant",
    "Previous similar crime",
    "Criminal method",
    "Additional criminal method",
    "Completion of crime",
    "# killed",
    "# injured",
    "Charges",
    "Plea",
    "Verdict",
    "Length of prison sentence",
    "Life sentence",
    "Death sentence",
    "Additional details",
    "Age",
    "Gender",
    "Other' status",
    "Racial/ethnic group",
    "Religion",
    "Veteran status",
    "Combat veteran",
    "Service Classification",
    "Citizenship status",
    "Short narrative",
    "Name of coder(s)",
    "Source description",
]